# To use:
#
#   $ conda env create -f environment.yml
#   $ conda activate vampire-analysis-dev-doc
#
name: vampire-analysis-dev-doc
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip>=22
  # packages imported by vampire
  # version pinned for resolving env faster
  - numpy>=1.22
  - pandas>=1.4
  - scipy>=1.0
  - matplotlib>=3.5
  - opencv>=4.5
  - scikit-image>=0.18
  - scikit-learn>=1.0
  # documentation
  - nbsphinx
  - pydata-sphinx-theme==0.13.3
  - numpydoc==1.5.0
  - myst-parser==1.0.0