# To use:
#
#   $ conda env create -f environment.yml
#   $ conda activate vampire-analysis-dev-doc
#
name: vampire-analysis-dev-doc
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  # documentation
  - sphinx
  - nbsphinx
  - pydata-sphinx-theme==0.13.3
  - numpydoc
  - myst-parser