# To use:
#
#   $ conda env create -f environment.yml
#   $ conda activate vampire-analysis-dev-doc
#
name: vampire-analysis-dev-doc
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  # packages imported by vampire
  # version pinned for resolving env faster
  - numpy==1.24
  - pandas==2.0
  - scipy==1.10
  - matplotlib==3.7
  - opencv==4.7
  - scikit-image==0.20
  - scikit-learn==1.2
  # documentation
  - sphinx
  - nbsphinx
  - pydata-sphinx-theme==0.13.3
  - numpydoc==1.5
  - myst-parser==1.0