# To use:
#
#   $ conda env create -f environment.yml
#   $ conda activate vampire-analysis-dev-doc
#
name: vampire-analysis-dev-doc
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip==23.1.2
  # packages imported by vampire
  # version pinned for resolving env faster
  - numpy==1.24
  - pandas
  - scipy==1.10
  - matplotlib==3.7
  - opencv==4.6
  - scikit-image
  - scikit-learn
  # documentation
  - nbsphinx
  - pydata-sphinx-theme==0.13.3
  - numpydoc==1.5.0
  - myst-parser==1.0.0