# To use:
#
#   $ conda env create -f environment.yml
#   $ conda activate vampire-analysis-dev-doc
#
name: vampire-analysis-dev-doc
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - libgfortran==5.0.0.dev0  # pin version to avoid numpy ImportError
  # basic data science
  - numpy
  - pandas
  - scipy
  - matplotlib
  - opencv
  - scikit-image
  - scikit-learn
  - openpyxl  # for reading excel in pandas
  # documentation
  - sphinx
  - nbsphinx
  - pydata-sphinx-theme==0.13.3
  - numpydoc
  - myst-parser